openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows the user to create and manage a TODO list using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /api/todos:
    get:
      operationId: getTodos
      summary: Get the list of todos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
  /api/eth-gpt:
    post:
      operationId: resolveName
      summary: Resolve the ENS name to address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resolveNameRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resolveNameResponse'
  /api/create-todo:
    post:
      operationId: addTodo
      summary: add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTodoRequest'
      responses:
        "200":
          description: OK
  /api/delete-todo:
    post:
      operationId: deleteTodo
      summary: delete a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteTodoRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    deleteTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to delete from the list.
          required: true
    addTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.
    resolveNameRequest:
      type: object
      properties:
        ensName:
          type: string
          description: The ENS name we are trying to resolve.
    resolveNameResponse:
      type: object
      properties:
        address:
          type: string
          description: The Ethereum address of that requested ENS name resolves to.